name: bewasserungv1
description: Ein modernes Flutter-Projekt zur Steuerung der Gartenbewässerung via RPI PICO W
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  json_annotation: ^4.8.0
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.5.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
